### ISSUE TITLE
needed to change evt.touches to evt.originalEvent.touches throughout

### ISSUE THREAD

**Issue by ostermanj** [ktknest/angular-pinch-zoom#3]
I'm not sure exactly why, but I was getting errors using this that amounted to evt.touches being undefined. I found advice elsewhere (e.g., here http://stackoverflow.com/questions/6173382/cant-able-to-get-the-properties-of-touchstart-event) that JQuery doesn't bring the touches array to its event object and that you need to access it through originalEvent. Seems odd since you don't seem to be invoking JQuery. The app I'm using it in does, so maybe there was conflict somehow (?). Changing all instances of evt.touches to evt.originalEvent.touches did get the directive working for me.

**Comment by ktknest** [comment]
@ostermanj 
Thank you for a issue!
I have released a new version (`v.0.2.1`) with bug fixes.
